db.url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
db.password=${MYSQL_PASSWORD}
db.user=${MYSQL_USER}
//db.password=${MYSQL_PASSWORD}